package com.hackathon.projecttron;

import android.app.Activity;
import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Point;
import android.media.AudioManager;
import android.os.Bundle;
import android.os.Handler;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;

import com.google.android.glass.media.Sounds;
import com.google.android.glass.widget.CardBuilder;
import com.google.android.glass.widget.CardScrollAdapter;
import com.google.android.glass.widget.CardScrollView;

import org.apache.http.entity.StringEntity;
import org.apache.http.util.EntityUtils;
import org.json.JSONObject;
import android.os.AsyncTask;
import android.util.Log;
import org.apache.http.*;
import org.apache.http.client.methods.*;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import org.apache.http.impl.client.DefaultHttpClient;
import java.util.ArrayList;

/**
 * An {@link Activity} showing a tuggable "Hello World!" card.
 * <p/>
 * The main content view is composed of a one-card {@link CardScrollView} that provides tugging
 * feedback to the user when swipe gestures are detected.
 * If your Glassware intends to intercept swipe gestures, you should set the content view directly
 * and use a {@link com.google.android.glass.touchpad.GestureDetector}.
 *
 * @see <a href="https://developers.google.com/glass/develop/gdk/touch">GDK Developer Guide</a>
 */
public class MainActivity extends Activity {

    /**
     * {@link CardScrollView} to use as the main content view.
     */
    private CardScrollView mCardScroller;

    public static final String URL = "http://104.131.15.54:5000/";
    public static final String TAG = "TRONMainActivity";
    /**
     * "Hello World!" {@link View} generated by {@link #buildView()}.
     */
    public float posX;
    public float posY;
    public float counter;

    private View mView;
    private ArrayList<Point> myPath = new ArrayList<Point>();
    private ArrayList<Point> hisPath = new ArrayList<Point>();
<<<<<<< HEAD
    private boolean running;
    private float posX;
    private float posY;
=======
>>>>>>> 10f8b992b15b0d6553a4e5ea0ef6a7b59b3915de
    private float yAug;
    private float xAug;
    private boolean running;
    public static String response;


    private Handler handler;
    private Handler posHandler;
    @Override
    protected void onCreate(Bundle bundle) {
        super.onCreate(bundle);

        running = true;
        counter = 0;
        mView = buildView();

        mCardScroller = new CardScrollView(this);
        mCardScroller.setAdapter(new CardScrollAdapter() {
            @Override
            public int getCount() {
                return 1;
            }

            @Override
            public Object getItem(int position) {
                return mView;
            }

            @Override
            public View getView(int position, View convertView, ViewGroup parent) {
                return mView;
            }

            @Override
            public int getPosition(Object item) {
                if (mView.equals(item)) {
                    return 0;
                }
                return AdapterView.INVALID_POSITION;
            }
        });
        // Handle the TAP event.
        mCardScroller.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                // Plays disallowed sound to indicate that TAP actions are not supported.
                AudioManager am = (AudioManager) getSystemService(Context.AUDIO_SERVICE);
                am.playSoundEffect(Sounds.DISALLOWED);
            }
        });
        setContentView(mCardScroller);
        handler = new Handler();
        handler.post(new Runnable(){
            @Override
            public void run() {
<<<<<<< HEAD
                if(running){
=======
                if (running){
>>>>>>> 10f8b992b15b0d6553a4e5ea0ef6a7b59b3915de
                    yAug = posY - 180;
                    xAug = posX - 320;
                }
                handler.postDelayed(this, 500);
            }
        });
<<<<<<< HEAD
=======

        posHandler = new Handler();
        posHandler.post(new Runnable(){
            @Override
            public void run(){
                if (running){
                    ProjectTronTaskGet netTask = new ProjectTronTaskGet();
                    ProjectTronTaskPost netTaskPost = new ProjectTronTaskPost();
                    Log.d(TAG, netTask.execute().toString());
                    Log.d(TAG, netTaskPost.execute(new Float[] {posX, posY, counter}).toString());
                }
                posHandler.postDelayed(this, 1000);
            }
        });
>>>>>>> 10f8b992b15b0d6553a4e5ea0ef6a7b59b3915de
    }

    @Override
    protected void onResume() {
        super.onResume();
        mCardScroller.activate();
    }

    @Override
    protected void onPause() {
        mCardScroller.deactivate();
        super.onPause();
    }

    public void onDead() {

    }

    /**
     * Builds a Glass styled "Hello World!" view using the {@link CardBuilder} class.
     */
    private View buildView() {
        //CardBuilder card = new CardBuilder(this, CardBuilder.Layout.TEXT);
        Canvas c = new Canvas();
        Paint paint = new Paint();
        paint.setStyle(Paint.Style.FILL);
        paint.setAntiAlias(true);

        paint.setColor(Color.GREEN);
        c.drawCircle(320, 180, 25, paint);

        paint.setColor(Color.BLUE);
        for (int i = 0; i < myPath.size(); i++){
            if (i > 0){
                Point pp = myPath.get(i-1);
                Point tp = myPath.get(i);
                c.drawLine(pp.x + xAug, pp.y + yAug, tp.x, tp.y, paint);
            }
        }
        paint.setColor(Color.RED);
        for (int i = 0; i < hisPath.size(); i++){
            if (i > 0){
                Point pp = hisPath.get(i-1);
                Point tp = hisPath.get(i);
                c.drawLine(pp.x + xAug, pp.y + yAug, tp.x, tp.y, paint);
            }
        }

        View v = new View(this);
        v.draw(c);

        return v;
    }

    private class ProjectTronTaskGet extends AsyncTask<String, Void, String>{


        @Override
        protected String doInBackground(String... urls){
            String response = "";
            DefaultHttpClient client= new DefaultHttpClient();
            HttpGet httpGet = new HttpGet(URL);

            try{
                HttpResponse execute = client.execute(httpGet);
                InputStream content = execute.getEntity().getContent();

                BufferedReader buffer = new BufferedReader(new InputStreamReader(content));

                String s = "";

                while((s = buffer.readLine()) != null){
                    response += s;
                }
            }
            catch (Exception e){
                Log.d(TAG, e.toString());
            }

            return response;
        }

        @Override
        protected void onPostExecute(String result){
            response = result;
            Log.d(TAG, "IN POST EXECUTE - " + response);
        }
    }

    private class ProjectTronTaskPost extends AsyncTask<Float, Void, String>{
        private JSONObject result;


        @Override
        protected String doInBackground(Float... args){
            postData(args[0], args[1], args[2]);
            return null;
        }

        @Override
        protected void onPostExecute(String result){
            response = result;
            Log.d(TAG, "IN POST EXECUTE - " + response);
        }

        public void postData(float posX, float posY, float counter){
            DefaultHttpClient client = new DefaultHttpClient();
            JSONObject coordinates = new JSONObject();
            Log.d(TAG,"IN POST DATA " + posX + " " + posY + " " + counter);

            try{
                coordinates.put("posX", posX);
                coordinates.put("posY", posY);
                coordinates.put("_id", "player_one");
                coordinates.put("counter", counter);

                HttpPost request = new HttpPost(URL + "coordinates");
                StringEntity params = new StringEntity(coordinates.toString());
                request.setEntity(params);

                HttpResponse response = client.execute(request);
                HttpEntity entity = response.getEntity();
                String stringEntity = EntityUtils.toString(entity);

                result = new JSONObject(stringEntity);
            }

            catch (Exception ex){
                Log.d(TAG, ex.toString());
            }
        }

    }
}
